version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "403unlockercli-linux"  # Unique ID for this build
    main: ./cmd
    binary: "403unlocker"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 403unlocker-cli/cmd/cli.Version={{ .Version }}

  - id: "403unlockercli-windows"  # Unique ID for this build
    main: ./cmd
    binary: "403unlocker"
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -X 403unlocker-cli/cmd/cli.Version={{ .Version }}

  - id: "403unlockercli-darwin"  # Unique ID for this build
    main: ./cmd
    binary: "403unlocker"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 403unlocker-cli/cmd/cli.Version={{ .Version }}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
